# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

In [2]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [3]:
print(type(A))
print()
print("Dimension:", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

<class 'numpy.ndarray'>

Dimension: 2
Shape: (3, 5)
Size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
print(B-C)
print()
print(B*C)
print()
print(B@C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("Exponentiated:", np.exp(B), "\n\n",
      "Min value:", np.min(B), "\n\n",
      "Min value in each row:", np.min(B, axis=1), "\n\n",
      "Min value in each column", np.argmin(B, axis=0), "\n\n",
      "Index value in the rows:", np.argmin(B, axis=1), "\n\n",
      "Sum of all elements: ", np.sum(B), "\n\n",
      "Mean:", np.mean(B, axis=0), "\n\n",
      "Median:", np.median(B, axis=0))

Exponentiated: [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

 Min value: 1 

 Min value in each row: [1 4 7] 

 Min value in each column [0 0 0] 

 Index value in the rows: [0 0 0] 

 Sum of all elements:  45 

 Mean: [4. 5. 6.] 

 Median: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [10]:
#A[1] samma sak som A[1,:], man vill ha ut hela raden.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [15]:
#Koden a är en en-dimensionell array som räknar från 0 till 29

#Koden b gör att koden a ändras till en tre-dimensionell array med hjälp av reshape funktionen.

#I funktionen har det bestämts att det ska staplas 2d arrays på varandra och att dessa arrays ska inneha 3 rader vardera.
#-1 betyder att dimensionens storklek beräknas automatiskt baserat på arrayens totala storlek och de andra angivna dimensionerna. 
#I detta fall blev det 5 kolumner.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [17]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [18]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [19]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [44]:
import numpy as np

def add_mult_matrices(A, B, operation=None):
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise TypeError("Both input matrices must be numpy arrays.")
    
    if operation not in ['add', 'multiply']:
        raise ValueError("Invalid operation. Use 'add' or 'multiply'.")
    
    if operation == 'add':
        if A.shape != B.shape:
            raise ValueError("Matrices must have the same shape for addition.")
        return np.add(A, B)
    elif operation == 'multiply':
        if A.shape[1] != B.shape[0]:
            raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix for multiplication.")
        return np.matmul(A, B)

In [52]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result_addition = add_mult_matrices(B, (-2) * A, 'add')
print("Matrix Addition Result:")
print(result_addition)

Matrix Addition Result:
[[3 2]
 [1 0]]


**Chap2. Question 2**

In [30]:
A = np.array([[1,2],
              [2,4]])

B = np.array([[2,1],
              [1,3]])

C = np.array([[4,3],
              [0,2]])

print(A@B)
print(A@C)
print(B@C)

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]
[[8 8]
 [4 9]]


**Chap2. Question 3**

In [31]:
A = np.array([1,1,1,1,2,3,1,3,4]).reshape(3,3)
D = np.array([2,0,0,0,3,0,0,0,4]).reshape(3,3)

print(A@D)
print(D@A)

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [32]:
mp1= np.array([[1,-1],
               [-1,1]])

mp2= np.array([[-1,1],
               [1,-1]])

mp1@mp2 

array([[-2,  2],
       [ 2, -2]])

**Chap 6. Question 1**

In [33]:
A= np.array([[5,6],
             [4,5]])

B= np.array([[6,4],
             [3,3]])

print(np.linalg.inv(A))
print(np.linalg.inv(B))

[[ 5. -6.]
 [-4.  5.]]
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [34]:
import numpy as np

A = np.array([[2, 2],
              [1, 2]])

A_i = np.linalg.inv(A)

In [35]:
A@A_i

array([[1., 0.],
       [0., 1.]])

**Chap10. Question 1 a)**

In [36]:
A= np.array([3,-7,-2,-3,5,1,6,-4,0]).reshape(3,3)
b= np.array([-7,5,2])

x = np.linalg.solve(A,b)

print(x)

[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [37]:
A= np.array([1,-2,+3,-1,3,-1,2,-5,5]).reshape(3,3)
b= np.array([1,-1,1])

x = np.linalg.solve(A,b)

print(x)

[ 8.  2. -1.]


**Chap 12. Question 1**

In [38]:
chap_12 = np.array([3,-7,-2,-3,5,1,6,-4,0]).reshape(3,3)

print(np.linalg.inv(chap_12))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [39]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [40]:
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [41]:
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
